name: Build
on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install
      - name: Test and coverage
        run: jest --watchAll --detectOpenHandles --forceExit --coverage --coverageReporters=lcov
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets. SONARCLOUD_TOKEN }}